### ISSUE TITLE
several more movie sites

### ISSUE THREAD

**Issue by ran88dom99** [grahamjenson/list_of_recommender_systems#21]
https://games.criticker.com/ (movies too)
https://movielens.org/ (end user lenskit movie site)

**Comment by ran88dom99** [comment]
Can someone without much statistical knowledge run any of these open source libraries on their computer? So that user could for example keep their ratings private or be sure the data base is not shifting under him?

**Comment by ran88dom99** [comment]
all MAL based
http://affinity.animesos.net/ similarity only no rec
https://graph.anime.plus/ there is rec too
http://www.animerecs.com/

**Comment by grahamjenson** [comment]
Could you please organize these and put into a PR?

**Comment by ran88dom99** [comment]
I did. Didn't I?

**Comment by grahamjenson** [comment]
Yup, and merged. Cheers :)

**Comment by ran88dom99** [comment]
and now about 70 more
[recommender-systems-apps-for-the-end-user](https://alternativeto.net/list/2554/recommender-systems-apps-for-the-end-user-/#ForumForm)

Maybe adding these directly to your list may not be the best idea? 

Made with AlternativeTo

Recommendation apps for the end user.

When want to know which movie or music to try next and want an app to give you recommendations with the power of math. The official term is 'recommender systems'. I am studying them so I made this list.

    I do not know
    topcorn.io

    Free Personal Web Website

    idunno. maybe exist way too many movie rec sites
    Facebook icon
    Facebook

    Free Web Android iPhone Blackberry Android Tablet ... Website

    poor other people recommender
    Bast icon
    Bast

    Free Android Opera Website

    Welcome to the simplest way to discover the latest top trending viral videos that the Internet (YouTube) has to offer.
    Bast, named after the ancient god of entertainment (Bastat), uses advanced algorithms to round up the most watched viral videos and allow you to see what's trending before anyone else.

    Features:
        Watch the newest and hottest viral videos of the web
        Filter your viral videos by day, week, month, year and all time
        See what videos are currently trending
        Save videos to a favorites list
        In a hurry? Mark your favorite videos and watch them later
        Really bored? Watch completely random videos, you'll never know what you come across
        Get social and share your favorite videos through Facebook, Twitter, Google + and more
    IsItGood icon
    IsItGood

    Free Web Website

    not finished yet
    The social discovery and personalized recommendation platform for podcasts.
    As you listen, our unique algorithm learns your taste over time.
    themoviedb.org icon
    themoviedb.org

    Free Web Website

    How do you build my recommendations?

    The more movies and TV shows you mark as a favorite, the more entries we can recommend for you. We will also automatically filter your rated items as well so you can hopefully find something new to watch instantly. Adding a minimum of 30 items will usually start to build an interesting list.
    ccshowtime icon
    ccshowtime

    Free Web Website

    will have similarity in future?
    TOP250 icon
    TOP250

    Free Personal Web Website

    I don't feel like rating 40 movies shows. Otherwise definate personalized recommendation score.
    Aventrix icon
    Aventrix

    Free Web Website

    Aventrix makes it easy to discover new and fun activities, whether you're looking for a fun night out with friends, an exciting date night, or a quiet evening at home. Aventrix connects you with local shows, concerts, and sports games as well as at-home entertainment like movies, video games, music, and books. Designed for easy use on laptops, tablets, and mobile devices, the Aventrix website makes it easy to discover, rate, save, and share activities wherever you are.
    Simkl TV Tracker icon
    Simkl TV Tracker

    Free Mac OS X Windows Linux Web Android ... Website

    Really pretty site. "Select personalized recommendations from 150,000 Movies, 38,000 TV shows and 8,000 Anime shows"
    Taste.io icon
    Taste.io

    Free Web Website

    Taste.io is a personalized movie recommendation app. Unlike the major rating sites, this suggestion engine is designed to return personalized matches with no commercial bias.
    And Chill icon
    And Chill

    Free Web Facebook Messenger Website

    doesnt work
    Bandcamp Recommender icon
    Bandcamp Recommender

    Free Web Website

    existed but now dead?
    Basic tag & Genre
    StumbleUpon icon
    StumbleUpon

    Free Windows Linux Web Android iPhone ... Website

    Website rec. Very simple content based and similarity.
    foursquare icon
    foursquare

    Free Web Android iPhone Blackberry Telegram ... Website

    selection by tag and follow user
    Goodreads icon
    Goodreads

    Free Web Android iPhone Android Tablet iPad Website

    Merged with Shelfari to gain tag based recommendation.
    Refind icon
    Refind

    Free Web Android iPhone Android Tablet iPad ... Website

    magazine of the most relevant ones for you—based on the people, hashtags, and publishers you follow. smart reading list helps you read better
    Steam icon
    Steam

    Freemium Mac Windows Linux Web Android ... Website

    basic tag based recommender
    Flavorit icon
    Flavorit

    Free iPhone Website

    Recommend:
    Discovered a new place a friend will love? Let them know about it. Plus, keep all your recommendations in one place.
    Locish icon
    Locish

    Free Android iPhone Website

    an new user suggest every time local question asked
    Curated
    WikiMentions icon
    WikiMentions

    Free Web Website

    WikiMentions lets you discover books/people/videos mentioned by great people. It’s a graph of mentions where people mention other people/books/videos in books/videos. Also it’s a wiki so anyone can add content. We already have around 2200 books and 1250 videos of 980 people. You can add content without signing up. You only need to sign up to edit or delete something.
    Film Fish icon
    Film Fish

    Free Web iPhone Website

    pretty good curated content based movies n tv
    Book Summaries icon
    Book Summaries

    Free Web Website

    Curation of best quotes from books.
    Bookicious icon
    Bookicious

    Free Web Website

    Browse our incredible book collections for makers and founders including books about startups, design and much more.
    Games Finder icon
    Games Finder

    Free Web Website

    just a set of curated lists of games
    Find Me Similar icon
    Find Me Similar

    Free Personal Web Website

    expert? curated similarity lists mov ani gam neh
    Dinevore icon
    Dinevore

    Free Web Website

    broken but may be really good
    Lists Curated by users.
    Anime-Planet icon
    Anime-Planet

    Free Web Website

    User made Item-Item suggestions.
    Listal icon
    Listal

    Free Web Website

    Lists of just about every single media.
    Slant icon
    Slant

    Free Web Website

    collaborative rec list editing includes shopping help
    Item-Item and Tag
    MyMovieRack icon
    MyMovieRack

    Free Web Website

    thorough set of feeling tags. not really good but novel.
    Similarkind icon
    Similarkind

    Free Web Website

    item item similarity lists for just about every type of entertainment
    Music Artist Cloud icon
    Music Artist Cloud

    Free Web Website

    Music dicovery using similar artists wordcloud. meh
    SimilarSites icon
    SimilarSites

    Free Mac Windows Linux Web Website

    tag based item-item websites
    What Should I Read Next? icon
    What Should I Read Next?

    Free Web Website

    tag based item item for books
    Yandex.Music icon
    Yandex.Music

    Freemium Web Android iPhone Android Tablet Windows Phone ... Website

    By genre, band similarity and possibly user listening history.
    Televisor icon
    Televisor

    Free Web Website

    poor content
    Amazon icon
    Amazon

    Free Web Android iPhone Android Tablet Windows Phone ... Website

    lots o poor item-item recommenders
    TopMoviesLike icon
    TopMoviesLike

    Free Mac OS X Windows Web Website

    movie Item-Item similarity
    Hunch

    Free Web Website

    dead? all sites similarity
    Collaborative Filtering (user-user)
    ViewerReviews icon
    ViewerReviews

    Free Web Website

    With the internet today, users are inundated with movie review sites that offer many ratings and reviews that range from "I loved it!" to "I hated it" which leaves them more confused than ever before.

    ViewerReviews members are identified by how compatible their tastes are in movies. They can follow compatible people to discover other movies and get personalized recommendations they are sure to enjoy.
    FilmAffinity icon
    FilmAffinity

    Free Personal Web Website

    Moderately advaced similarity.
    Criticker icon
    Criticker

    Free Web Website

    The TCI is a measure of the similarity between two people's taste in films. The lower the TCI, the greater the tendency to agree on which movies ruled and which sucked.

    Once you've ranked a handful of movies at Criticker, you can generate TCIs with everyone in the community -- both normal users and published critics. It's better than just finding a few people with whom you generally agree -- Criticker will show you the exact people whose tastes are the most similar to your own. It's scientific (kind of)!

    Want to see the details on how we generate TCIs?
    Itcher icon
    Itcher

    Free Web Android iPhone Android Tablet iPad Website

    itcher is a movie, book, music and game recommendations app that uses the power of its community to provide results based on your personal taste. With a database of more than 4 million titles, itcher gives you your first community powered recommendations in less than 50 seconds.
    MyAnimeList icon
    MyAnimeList

    Freemium Web Android iPhone Android Tablet iPad Website

    There are many unofficial addons for it including recommenders like http://affinity.animesos.net/ finds people with similar taste, https://graph.anime.plus/ and https://graph.anime.plus/ which recommend anime based on item item similarity.
    TasteDive icon
    TasteDive

    Free Web TasteDroid Website

    TasteDive (formerly TasteKid) is a recommendation engine for music, movies, authors and books. Just type in your favorite bands, artists, movie titles, book titles or authors, separated by commas, and TasteDive will suggest other things that you may enjoy.

    You can easily form a first impression on the recommended items by checking out the short description or the video clip (only available over WiFi connections) in the details page. Explore your taste!
    TINQ icon
    TINQ

    Free Android iPhone Website

    Its in Turkish I think but the alt.to page says its got similarity.
    Kaboodle.io icon
    Kaboodle.io

    Free Web Website

    Discover Find users with high affinity and discover movies and tv shows.
    Weaker user user?
    iRate Radio icon
    iRate Radio

    Free Mac OS X Windows Linux Website

    The iRATE server then selects other tracks to send to the user from a database of over 50,000 freely downloadable songs by correlating the user's ratings with other users', and finding people with similar tastes.
    Item Item similarity graph
    Yasiv icon
    Yasiv

    Free Web Website

    Much better than base amazon item- item rec map.
    Project Alexandria

    Free Web Website

    Like that music item similarity graph.
    Discovr Music icon
    Discovr Music

    Commercial iPhone iPad Website

    Music similarity graph. meh
    LivePlasma icon
    LivePlasma

    Free Web Website

    silly band proximity map
    Reddit icon
    Reddit

    Freemium Web Android iPhone Android Tablet iPad Website

    http://ponderinghydrogen.pythonanywhere.com/ Dimensionality reduction 2D map and recommender of subreddits.
    Advanced Algorithms inc Factorization
    Movix icon
    Movix

    Free Web Website

    LSTM recurrent neural network. only needs 1 fave movie or more and can deal with down votes. works pretty well
    MovieLens icon
    MovieLens

    Free Web Website

    MovieLens helps you find non-commercial, personalized movie recommendations. Rate movies to build a custom taste profile, then MovieLens recommends other movies for you to watch.
    Coollector Movie Database icon
    Coollector Movie Database

    Commercial Mac OS X Windows Website

    Coollector Movie database is the most complete tool for the movie lovers. It's a huge database of movies and series, personalized with what you've seen, how much you've liked it, and what you wish to see. It's also a video collection manager, to track what DVDs you own, where they're stored, and which ones you've loaned. It can handle your digital collection too, with a lightning-fast file scanning feature. Last but not least, it'll analyze your taste to give you the best movie recommendations you've ever had.
    Netflix icon
    Netflix

    Commercial Windows Web Android iPhone Chrome OS ... Website

    How can anyone forget the Netflix Million Dollar recommendation system prize?
    Smovault icon
    Smovault

    Free Personal Windows Website

    Smovault is primarily a movie recommendation and logging software. However it goes beyond what existing software are capable of. Smovault is innovative not only with its easy user interface, but also the smart algorithms help you by recommending movies based on your taste.
    Google Search icon
    Google Search

    Free Windows Web Android iPhone Chrome OS ... Website

    its a recommender system too
    Gnoosic icon
    Gnoosic

    Free Web Website

    Even if you don't know what you are looking for - gnod will find it.
    Gnod is a self-adapting system that learns about the outer world by asking its visitors what they like and what they don't like. In this instance of gnod all is about music. Gnod is kind of a search engine for music you don't know about. It will ask you what music you like and then think about what you might like too. When I set gnod online its database was completely empty. Now it contains thousands of bands and quite some knowledge about who likes what. And gnod learns more every day.
    Pandora icon
    Pandora

    Freemium Mac Windows Web Android iPhone ... Website

    Pandora Radio is a free (ad-supported) internet radio founded in 2000. Using the Music Genome Project, over 400 attributes of songs are analyzed in order to personalize radio stations from music you like.

    For $4.99/month you can upgrade to Pandora One and enhance your experience with these new features:

        High Quality Streaming: When listening on the web, experience 192K bits per second audio.

        Pandora One Desktop: Listen to Pandora from a dedicated desktop application; no need to keep a browser window open. Control playback from the Windows taskbar or the Macintosh dock. Get popup alerts when a new song starts to play.

        No Ads: Pandora One is completely free of any sort of advertising: no audio ads, no visual ads. Its just you and your music.

        Personalize Your Look: Surround the Pandora player with one of 8 custom "skins" that will make the look of Pandora as personalized as the music.

        Mini Player: Minimize Pandora One into the smallest possible browser window. This makes it easy for the web version of Pandora to live side by side with other web sites and applications.

        Skip All Day Long: With the standard ad supported version of Pandora youre limited to 12 total skips per day. With Pandora One youll be able to skip as many times per day as youd like (note you will still be limited, thanks to licensing constraints, to six skips per hour).

        Extended Interaction Timeout: Listen for up to 5 hours in a row without interacting with Pandora at all. Just turn it on and let it go. Every time you interact the timer is reset so just one click around lunchtime can get you through an entire workday.

    [Pandora is only available in the U.S., Australia and New Zealand.]
    Last.fm icon
    Last.fm

    Freemium Mac OS X Windows Linux Web Android ... Website

    Last.fm is a music community website that offers personalized internet radio, using a recommendation system called "Audioscrobbler" to build a detailed profile of users based on their music tastes and interests. The service installs plugins into the user's media player and automatically profiles the songs he/she listens to.
    The service will offer recommendations and a 'personal' radio station based on the user's listening patterns.

    As of early 2009 last.fm charges 3 EUR/month subscription fee to allow listening to music on their website outside US, UK and Germany. Paid features include:
        Unlimited radio streaming
        Ad-free browsing and streaming
        Recent visitors to your profile
        A prestigious black icon
        Access to the VIP zone with more charts, graphs and the latest from the Last.fm Labs

    See http://www.last.fm/subscribe
    Unique top lists
    BooksReddit icon
    BooksReddit

    Free Web Website

    BooksReddit is Reddit book recommendation aggregator. It lets you discover most popular books mentioned by people for different subjects.

    Suggested books are based on links found in user comments on Reddit. Products are rated by popularity based on upvotes and number of mentions. Search for most popular books on Reddit by year,category or subreddit.
    Cinesift icon
    Cinesift

    Free Web Website
    A Good Movie to Watch icon
    A Good Movie to Watch

    Free Web Website

    We pick movies that received high ratings both from viewers (IMDB) and critics (Rotten Tomatoes). In other words, really good movies

    We narrow them down to those that didn't make a huge splash at the box office. This way not only are the movies great, but you haven't seen them yet
    Goodfilms icon
    Goodfilms

    Free Web Website

    Critical vs fun ratings. Allows finding really fun schlocky movies. Not actually recommender system but main idea is worth remebering.
    Unique and interesting.
    Tribler icon
    Tribler

    Free Mac Windows Linux Website

    P2P decentralised rec sys. Run over bittorent i think.
    sopularity icon
    sopularity

    Freemium Windows Web Website

    Tag similarity and NLP? hastag for tweets finder.
    Bad, uninteresting, broken

https://alternativeto.net/list/2634/recommender-systems-as-service-to-sites

**Comment by ran88dom99** [comment]
also first 3 Media Recommendation Applications are SaaS and only non SaaS for profit is dead

**Comment by grahamjenson** [comment]
Can you organize and put into PR, cheers :)
